#! /bin/bash
sxhkd &
if xrandr -q | grep 'VGA1 connected'; then
    xrandr --output VGA1 --mode 1360x768 --left-of LVDS1
	bspc monitor LVDS1 -d web term chat code music 6 7 
    bspc monitor VGA1 -d I II III IV V VI VII
else
	bspc monitor LVDS1 -d web term chat code music 6 7 
fi
xrandr --output LVDS1 --mode 1366x768
bspc monitor LVDS1 -d web term chat code music 6 7 


bspc config border_width         0 
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          20

#bspc desktop ^1 -l monocle

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Subl desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Lmms desktop=^5
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a Eog state=floating
bspc rule -a Gpick state=floating
bspc rule -a albert focus=on
bspc rule -a plasmashell state=floating

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
#bspc config click_to_focus true
#bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr
 
feh --randomize --bg-fill ~/Pictures/walls/cars
compton --config ~/.config/compton.conf -b
setxkbmap -option "caps:swapescape"
redshift-gtk &
nm-applet &
polybar top &
if xrandr -q | grep 'VGA1 connected'; then
	polybar top2 &
fi
dbus-launch indicator-kdeconnect &
sleep 30 && gnome-screensaver &
 #enable autolock
sleep 30 && xautolock -time 3 -locker "/home/anoop/Documents/Scripts/locker.sh" -corners +0-0 -cornerdelay 15 -cornerredelay 5 -detectsleep &
 disable cappuccino if enabled
if [ -f "/home/anoop/Documents/Scripts/cappuccino" ];
    then rm -f "/home/anoop/Documents/Scripts/cappuccino" &
fi
/usr/lib/notification-daemon-1.0/notification-daemon &
sleep 35 && /home/anoop/Documents/Scripts/start_tasks.sh &
sleep 5 && /home/anoop/Documents/Scripts/rotate_wall.sh &
