#! /bin/bash
sxhkd &
bspc monitor -d web term chat code music 6 7 


bspc config border_width         0 
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          20

#bspc desktop ^1 -l monocle

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Subl desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Lmms desktop=^5
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a Eog state=floating
bspc rule -a Gpick state=floating
bspc rule -a albert focus=on
bspc rule -a plasmashell state=floating

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr
 
feh --randomize --bg-fill ~/Pictures/walls
#compton --config ~/.config/compton.conf -b
xcompmgr -n &
setxkbmap -option "caps:swapescape"
redshift-gtk &
nm-applet &
polybar top &
dbus-launch indicator-kdeconnect &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
